

# MI_TO image

################################################################

## Start Debian basic image: NBBB ricordarsi --platform linux/x86_64 in docker build
FROM python:3.9-bullseye

## Change as u want
LABEL mantainer = "andrea.cossa@ieo.it"

## Compilers, utilities, git
RUN apt-get --quiet update --yes \
    && apt-get --quiet upgrade --yes \
    && apt-get --quiet install --yes \
      libcurl4-openssl-dev \
      libssl-dev \
      libxml2-dev \
      build-essential \
      libz-dev \
      wget \
      procps \
      git \
      cmake \
    && rm -rf /var/lib/apt/lists/*

## Mamba
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh \
    && bash Mambaforge-Linux-x86_64.sh -b -p /mambaforge
ENV PATH="/mambaforge/bin/:$PATH"

## Clone repo and install code
RUN echo hyperopt added
RUN git clone https://github.com/andrecossa5/MI_TO.git \
    && cd MI_TO \
    && mamba env update -n base -f envs/environment.yml \
    && mamba develop .. \
    && mamba develop ../MI_TO/ 

# RUN pipelines/genomics utils
RUN apt-get --quiet update --yes \
    && apt-get --quiet upgrade --yes \
    && apt-get --quiet install --yes pigz

RUN mamba install --yes -c bioconda samtools
RUN pip install dnaio pysam
RUN mamba install --yes -c conda-forge openjdk
RUN mamba install --yes -c bioconda snakemake fgbio 
RUN git clone https://github.com/caleblareau/maegatk.git 
RUN mamba install --yes -c bioconda bedtools bwa

## Default command to initialize the container
CMD [ "bash" ]

#################################################################












1. Download FRACTAL by

   ```shell
    git clone https://github.com/yachielab/FRACTAL.git
   ```

   or you can also obtain FRACTAL as follows

   ```shell
    wget https://github.com/yachielab/FRACTAL/archive/master.zip
    unzip master.zip
   ```

2. Add the absolute path of `FRACTAL` directory to `$PATH`

3. Make `FRACTAL` executable

   ```shell
   chmod u+x FRACTAL
   ```

#### Installation of [Anaconda](https://www.anaconda.com/distribution/) (required)

1. Execute the following commands

    ```shell
    wget https://repo.anaconda.com/archive/Anaconda3-2018.12-Linux-x86_64.sh
    bash Anaconda3-2018.12-Linux-x86_64.sh
    bash
    ```

2. Set `$PATH` to `anaconda3/bin`.

#### Installation of [Biopython](https://anaconda.org/anaconda/biopython) (required)

1. Install Biopython by

   ```shell
   conda install biopython
   ```

#### Installation of [RAxML](https://github.com/stamatak/standard-RAxML) (required)

1. Execute the following commands

   ```shell
   wget https://github.com/stamatak/standard-RAxML/archive/master.zip
   unzip master.zip
   cd standard-RAxML-master
   make -f Makefile.SSE3.gcc
   rm *.o
   make -f Makefile.SSE3.PTHREADS.gcc
   rm *.o
   ```

2. Set `$PATH` to `raxmlHPC-SSE3` & `raxmlHPC-PTHREADS-SSE3` executable.

#### Installation of [EPA-ng](https://github.com/Pbdas/epa-ng) (required)

1. Install EPA-ng by

   ```shell
   conda install -c bioconda epa-ng
   ```

#### Installation of [Seqkit](https://bioinf.shenwei.me/seqkit/) (required)

1. Install Seqkit by

   ```shell
   conda install -c bioconda seqkit
   ```

#### Installation of [RapidNJ](http://birc.au.dk/software/rapidnj/) (optional)

1. Install RapidNJ

   ```
   conda install -c bioconda rapidnj
   ```

#### Installation of [FastTreeMP](http://www.microbesonline.org/fasttree/) (optional)

1. Execute the following commands

   ```shell
   wget http://www.microbesonline.org/fasttree/FastTreeMP
   chmod u+x FastTreeMP
   ```

2. Please set `$PATH` to `FastTreeMP` executable.

#### Installation of [MAFFT](https://mafft.cbrc.jp/alignment/software/) (optional)

1. Install MAFFT

   ```shell
   conda install -c bioconda mafft
   ```

#### Installation of [HMMER](http://hmmer.org/) (optional)

1. Install HMMER

   ```shell
   conda install -c bioconda hmmer
   ```

#### Installation of [trimAl](http://trimal.cgenomics.org/) (optional)

1. Install trimAl

   ```shell
   conda install -c bioconda trimal
   ```

